=== lazarev-pv/robot-game/Core/schemas/laf.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:include schemaLocation="common.xsd" />
    <xs:include schemaLocation="resources_description.xsd" />

    <xs:element name="lookAndFeel" type="LookAndFeelType"/>
    <xs:complexType name="LookAndFeelType">
        <xs:sequence>
            <xs:element name="resources" type="ResourceDescriptionList" />
            <xs:element name="defaultColor" type="ColorType" minOccurs="0"/>
            <xs:element name="font" type="FontLAFType" minOccurs="0"/>
            <xs:element name="buttons" type="ButtonLAFType" minOccurs="0"/>
            <xs:element name="dialogs" type="DialogsLAFType" minOccurs="0"/>
            <xs:element name="menu" type="MenuLAFType" minOccurs="0"/>
            <xs:element name="inputField" type="InputFieldLAFType" minOccurs="0"/>
            <xs:element name="checkbox" type="CheckboxLAFType" minOccurs="0"/>
            <xs:element name="slider" type="SliderLAFType" minOccurs="0"/>
            <xs:element name="rgbSlider" type="RGBSliderLAFType" minOccurs="0"/>
            <xs:element name="labelsList" type="LabelsListLAFType" minOccurs="0"/>
            <xs:element name="imagePicker" type="ImagePickerLAFType" minOccurs="0"/>
            <xs:element name="healthbar" type="HealthbarLAFType" minOccurs="0"/>
            <xs:element name="caption" type="CaptionLAFType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="FontLAFType">
        <xs:sequence>
            <xs:element name="textColor" type="ColorType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="size" type="xs:int"/>
        <xs:attribute name="face" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="ButtonStateLAFType">
        <xs:sequence>
            <xs:element name="font" type="FontLAFType" minOccurs="0"/>
            <xs:element name="backColor" type="ColorType" minOccurs="0"/>
            <xs:element name="borderColor" type="ColorType" minOccurs="0"/>
            <xs:element name="image" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="MenuLAFType">
        <xs:sequence>
            <xs:element name="font" type="FontLAFType" minOccurs="0"/>
            <xs:element name="normalColor" type="ColorType" minOccurs="0"/>
            <xs:element name="hoveredColor" type="ColorType" minOccurs="0"/>
            <xs:element name="borderColor" type="ColorType" minOccurs="0"/>
            <xs:element name="padding" type="PaddingType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="borderThickness" type="xs:float"/>
        <xs:attribute name="image"/>
        <xs:attribute name="hoverImage"/>
    </xs:complexType>

    <xs:complexType name="CheckboxLAFType">
        <xs:attribute name="normal_image"/>
        <xs:attribute name="checked_image"/>
        <xs:attribute name="hw" type="xs:float"/>
        <xs:attribute name="hh" type="xs:float"/>
    </xs:complexType>

    <xs:complexType name="RGBSliderLAFType">
        <xs:attribute name="hh" type="xs:float"/>
        <xs:attribute name="colorHW" type="xs:float"/>
    </xs:complexType>

    <xs:complexType name="SliderLAFType">
        <xs:sequence>
            <xs:element name="recColor" type="ColorType"/>
            <xs:element name="markColor" type="ColorType"/>
            <xs:element name="texColor" type="ColorType"/>
            <xs:element name="hoveredColor" type="ColorType"/>
        </xs:sequence>
        <xs:attribute name="baseHH" type="xs:float"/>
        <xs:attribute name="hh" type="xs:float"/>
        <xs:attribute name="markLen" type="xs:float"/>
        <xs:attribute name="defaultPercision" type="xs:int" default="2"/>
    </xs:complexType>

    <xs:complexType name="ButtonLAFType">
        <xs:sequence>
            <xs:element name="normal" type="ButtonStateLAFType" minOccurs="0"/>
            <xs:element name="hovered" type="ButtonStateLAFType" minOccurs="0"/>
            <xs:element name="pushed" type="ButtonStateLAFType" minOccurs="0"/>
            <xs:element name="padding" type="PaddingType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="borderThickness" type="xs:float"/>
        <xs:attribute name="animatedImage"/>
    </xs:complexType>

    <xs:complexType name="DialogsLAFType">
        <xs:sequence>
            <xs:element name="capture" type="DialogCaptureLAFType" minOccurs="0"/>
            <xs:element name="background" type="DialogBackgroundLAFType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="image"/>
    </xs:complexType>

    <xs:complexType name="DialogBackgroundLAFType">
        <xs:sequence>
            <xs:element name="backColor" type="ColorType" minOccurs="0"/>
            <xs:element name="borderColor" type="ColorType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="borderThickness" type="xs:float" default="0"/>
    </xs:complexType>

    <xs:complexType name="DialogCaptureLAFType">
        <xs:sequence>
            <xs:element name="font" type="FontLAFType" minOccurs="0"/>
            <xs:element name="color" type="ColorType" minOccurs="0"/>
            <xs:element name="controlButtons" type="ButtonLAFType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="height" type="xs:float" default="-1"/>
        <xs:attribute name="controlsWidth" type="xs:float" default="-1"/>
    </xs:complexType>


    <xs:complexType name="InputFieldLAFType">
        <xs:sequence>
            <xs:element name="font" type="FontLAFType" minOccurs="0"/>
            <xs:element name="backColor" type="ColorType" minOccurs="0"/>
            <xs:element name="disBackColor" type="ColorType" minOccurs="0"/>
            <xs:element name="selectColor" type="ColorType" minOccurs="0"/>
            <xs:element name="borderColor" type="ColorType" minOccurs="0"/>
            <xs:element name="selectedBorderColor" type="ColorType" minOccurs="0"/>
            <xs:element name="cursorColor" type="ColorType" minOccurs="0"/>
            <xs:element name="padding" type="PaddingType" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="borderThickness" type="xs:float"/>
        <xs:attribute name="cursorHW" type="xs:float"/>
        <xs:attribute name="image"/>
        <xs:attribute name="normal"/>
        <xs:attribute name="focused"/>
    </xs:complexType>

    <xs:complexType name="PaddingType">
        <xs:attribute name="left" type="xs:float" default="0.0"/>
        <xs:attribute name="top" type="xs:float" default="0.0"/>
        <xs:attribute name="right" type="xs:float" default="0.0"/>
        <xs:attribute name="down" type="xs:float" default="0.0"/>
    </xs:complexType>

    <xs:complexType name="LabelsListLAFType">
        <xs:sequence>
            <xs:element name="padding" type="PaddingType" />
            <xs:element name="normalTextColor" type="ColorType" />
            <xs:element name="selectedTextColor" type="ColorType" />
            <xs:element name="selectionColor" type="ColorType" />
            <xs:element name="backgroundColor" type="ColorType" />
            <xs:element name="borderColor" type="ColorType" />
            <xs:element name="scroller" type="ScrollerLAFType" />
        </xs:sequence>
        <xs:attribute name="borderWidth" type="xs:int" />
    </xs:complexType>

    <xs:complexType name="ScrollerLAFType">
        <xs:sequence>
            <xs:element name="backColor" type="ColorType" />
            <xs:element name="borderColor" type="ColorType" />
        </xs:sequence>
        <xs:attribute name="width" type="xs:int" />
        <xs:attribute name="height" type="xs:int" />
        <xs:attribute name="borderWidth" type="xs:int" />
        <xs:attribute name="hoveredImage" />
        <xs:attribute name="image" />
    </xs:complexType>

    <xs:complexType name="ImagePickerLAFType">
        <xs:sequence>
            <xs:element name="labelsOffset" type="Point3D" />
            <xs:element name="labelsSize" type="Point2D" />
            <xs:element name="imageBorderColor" type="ColorType" />
            <xs:element name="imageOffset" type="Point3D" />
            <xs:element name="imageSize" type="Point2D" />
            <xs:element name="baseSize" type="Point2D" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="HealthbarLAFType">
        <xs:attribute name="hh" type="xs:float" />
        <xs:attribute name="defaultPercision" type="xs:int" default="0"/>
        <xs:attribute name="image" />
        <xs:attribute name="backImage" />
        <xs:attribute name="borderThickness" type="xs:float" />
    </xs:complexType>

    <xs:complexType name="CaptionLAFType">
        <xs:sequence>
            <xs:element name="color" type="ColorType" />
            <xs:element name="textColor" type="ColorType" />
        </xs:sequence>
        <xs:attribute name="hh" type="xs:float" />

    </xs:complexType>
</xs:schema>

=== lazarev-pv/robot-game/Game-Data/game/ui/laf.xml
<lookAndFeel xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="laf.xsd">
    <resources>
        <font file="default.ttf" name="default" />
        <sprite file="ui.atlas" />
        <sprite file="common_icons.atlas" />
        <sprite file="cb_n.png" />
        <sprite file="cb_s.png" />
        <sprite file="hb.png" />
        <sprite file="menu.png" name="menu" top="8" left="8" right="8" bottom="8" />
        <sprite file="hb_back.png" name="hb_back" top="8" left="8" right="8" bottom="8" />
        <sprite file="menu_selection.png" name="menu_selection" top="8" left="8" right="8" bottom="8" />
        <sprite file="dialog.png" name="dialog" top="33" left="25" right="25" bottom="10" />
        <sprite file="scroller.png" top="2" left="2" right="2" bottom="2" />
        <sprite file="hovered_scroller.png" top="2" left="2" right="2" bottom="2" />
    </resources>
    <defaultColor hex="FFFFFF" />
	<font size="18" face="default" />
	<buttons borderThickness="0.005" animatedImage="buttons">
		<normal>
            <font size="18">
                <textColor hex="000000" />
            </font>
            <image>normal</image>
		</normal>
		<hovered>
            <image>hovered</image>
            <font size="18">
                <textColor hex="000000" />
            </font>
		</hovered>
		<pushed>
            <image>pushed</image>
            <font size="18">
                <textColor hex="000000" />
            </font>
		</pushed>
	</buttons>
	<dialogs image="dialog">
		<capture>
			<font size="18">
                <textColor hex="FFFFFF" />
            </font>
			<color hex="000000" a="0.4" />
		</capture>
		<background borderThickness="0.01" >
			<!--<backColor r="0.5" g="0.5" b="1" />-->
			<borderColor r="1" g="1" b="1" />
            <backColor hex="010101" a="0.4" />
		</background>
	</dialogs>	
    <menu image="menu" hoverImage="menu_selection">
        <font size="18">
           <textColor hex="FFFFFF" />
        </font>
        <padding top="4" bottom="4" left="5" right="5"/>
    </menu>
    <inputField 
        borderThickness="0.005" cursorHW="1"
        image="input" normal="normal" focused="focused" >
        <font size="18">
           <textColor hex="000000" />
        </font>
        <backColor hex="FFFFFF" />
        <disBackColor hex="BABAB3" />
        <selectColor hex="F8987C" a="1" />
        <borderColor hex="000000" />
        <selectedBorderColor hex="E75C2D" />
        <cursorColor hex="0000FF" />
        <padding left="7" top="0" right="7" down="0" />
    </inputField>	
    <checkbox normal_image="cb_n"
    		  checked_image="cb_s"
    		  hw="8"
    		  hh="8" />
 	<slider baseHH="7" hh="10" markLen="10" >
    	<recColor hex="000000" />	
    	<markColor hex="F4F3F3" />	
    	<texColor hex="FFFFFF" />	
    </slider>
    <labelsList borderWidth="2" >
        <padding left="10" top="7" right="10" down="7" />
        <normalTextColor hex="000000" />
        <selectedTextColor hex="FFFFFF" />
        <selectionColor hex="455ede" />
        <backgroundColor hex="FFFFFF" />
        <borderColor hex="999999" />
        <scroller image="scroller" hoveredImage="hovered_scroller" width="10" height="25" borderWidth="2">
            <backColor hex="f5f5f5"/>
            <borderColor hex="e6e6e6" />
        </scroller>
    </labelsList>
    <imagePicker>
        <labelsOffset x="-0.24" y="-0.00" z="0.1" />
        <labelsSize x="0.15" y="0.44"  />
        <imageBorderColor hex="999999" />
        <imageOffset x="0.15" y="0.00" z="0.1" />
        <imageSize x="0.19" y="0.35" />
        <baseSize x="0.4" y="0.5" />
    </imagePicker>
    <healthbar
            hh="10"
            image="hb"
            backImage="hb_back"
            borderThickness="8" />
    <caption hh="10" >
        <color r="0.1647" g="0.1647" b="0.1647" a="1.0" />
        <textColor hex="FFFFFF" />
    </caption>
</lookAndFeel>
