=== lazarev-pv/robot-game/Robot-Game/schemas/robot_config.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >

    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="weapons" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="weapon" type="WeaponType" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="characters" >
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="character" type="CharacterSettingsType" minOccurs="0" maxOccurs="unbounded" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="camera" type="CameraConfigType" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="ColdStateType">
        <xs:attribute name="duration" type="xs:float" />
        <xs:attribute name="p" type="xs:float" />
        <xs:attribute name="slowdown" type="xs:float" />
    </xs:complexType>

    <xs:complexType name="FireStateType">
        <xs:attribute name="duration" type="xs:float" />
        <xs:attribute name="p" type="xs:float" />
    </xs:complexType>

    <xs:complexType name="ShockStateType">
        <xs:attribute name="duration" type="xs:float" />
        <xs:attribute name="p" type="xs:float" />
    </xs:complexType>


    <xs:complexType name="WeaponUpgradeType">
        <xs:sequence>
            <xs:element name="fire" type="FireStateType" minOccurs="0" />
            <xs:element name="cold" type="ColdStateType" minOccurs="0" />
            <xs:element name="shock" type="ShockStateType" minOccurs="0" />
        </xs:sequence>
        <xs:attribute name="cost" type="xs:float" />
        <xs:attribute name="tier" type="xs:int" />
    </xs:complexType>

    <xs:complexType name="WeaponType">
        <xs:sequence>
            <xs:element name="upgrade" type="WeaponUpgradeType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" />
        <xs:attribute name="damage" type="xs:float" />
        <xs:attribute name="firingRate" type="xs:float" />
        <xs:attribute name="closeHanded" type="xs:boolean" />
        <xs:attribute name="collideSensor" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="CharacterSettingsType">
        <xs:sequence>
            <xs:element name="weapon" type="WeaponType" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" />
        <xs:attribute name="file" />
        <xs:attribute name="health" type="xs:float" />
        <xs:attribute name="jumpVelocity" type="xs:float" />
        <xs:attribute name="runVelocity" type="xs:float" />
        <xs:attribute name="animationMultiplier" type="xs:float" />
    </xs:complexType>

    <xs:complexType name="CameraConfigType">
        <xs:attribute name="xVelocity" type="xs:float" />
        <xs:attribute name="yVelocity" type="xs:float" />

        <!--<xs:attribute name="xForwardOffset" type="xs:float" />
        <xs:attribute name="xForwardOffsetVelocity" type="xs:float" />
        <xs:attribute name="xBackwardOffset" type="xs:float" />
        <xs:attribute name="xBackwardOffsetVelocity" type="xs:float" />
        <xs:attribute name="yOffset" type="xs:float" />
        <xs:attribute name="yOffsetVelocity" type="xs:float" />-->
    </xs:complexType>

</xs:schema>

=== lazarev-pv/robot-game/Game-Data/game/config.xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://localhost/schema/robot_config.xsd" >

    <weapons>
        <weapon
            name="bar"
            damage="10"
            firingRate="1.0"
            closeHanded="true"
            collideSensor="sword" />
        <weapon
            name="blaster"
            damage="20"
            closeHanded="false"
            />
        <weapon
            name="sword"
            damage="20"
            firingRate="1.5"
            closeHanded="true"
            collideSensor="sword" >

            <upgrade cost="100" tier="1" >
                <fire duration="2.0" p="0.2" />
            </upgrade>
            <upgrade cost="100" tier="1" >
                <cold duration="2.0" p="0.2" slowdown="0.5"/>
            </upgrade>
            <upgrade cost="500" tier="2" >
                <shock duration="2.0" p="0.2" />
            </upgrade>
        </weapon>
    </weapons>
    <characters>
        <character
            name="char"
            file="characters/char/char.xml"
            health="100"
            jumpVelocity="6"
            runVelocity="2.5"
            animationMultiplier="1.5" />

        <character
            name="zombie"
            file="characters/zombie/zombie.xml"
            health="30"
            jumpVelocity="5"
            runVelocity="1.2"
            animationMultiplier="1.0">

            <weapon
                damage="10"
                firingRate="1.5"
                closeHanded="true" />
        </character>

    </characters>

    <camera
        xVelocity="0.09"
        yVelocity="0.05"
        />
</config>
